#!/bin/sh
# Regenerate Formula/wt.rb for a release.
#
#   scripts/update-formula.sh <version> [asset-dir]
#
# asset-dir must contain the release tarballs (wt-<target>.tar.gz); it defaults
# to the current directory, which is where the release workflow downloads them.
set -e

VERSION="${1:?usage: update-formula.sh <version> [asset-dir]}"
VERSION="${VERSION#v}"
ASSET_DIR="${2:-.}"
REPO="listennn08/wt"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

sha() {
  file="${ASSET_DIR}/wt-$1.tar.gz"
  [ -f "$file" ] || { echo "missing release asset: $file" >&2; exit 1; }
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | cut -d' ' -f1
  else
    shasum -a 256 "$file" | cut -d' ' -f1
  fi
}

MACOS_ARM=$(sha aarch64-apple-darwin)
MACOS_X86=$(sha x86_64-apple-darwin)
LINUX_ARM=$(sha aarch64-unknown-linux-gnu)
LINUX_X86=$(sha x86_64-unknown-linux-gnu)

mkdir -p Formula
cat > Formula/wt.rb <<EOF
# Generated by scripts/update-formula.sh — do not edit by hand.
class Wt < Formula
  desc "Git worktree manager with an interactive TUI"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "ISC"

  # wt drives git as a subprocess rather than linking libgit2.
  depends_on "git"

  on_macos do
    on_arm do
      url "${BASE}/wt-aarch64-apple-darwin.tar.gz"
      sha256 "${MACOS_ARM}"
    end
    on_intel do
      url "${BASE}/wt-x86_64-apple-darwin.tar.gz"
      sha256 "${MACOS_X86}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/wt-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/wt-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X86}"
    end
  end

  def install
    bin.install "wt"
    generate_completions_from_executable(
      bin/"wt", "completion",
      shells: [:bash, :zsh, :fish],
      shell_parameter_format: :none,
    )
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wt --version")
    system bin/"wt", "list", "--help"
  end
end
EOF

echo "wrote Formula/wt.rb for v${VERSION}"
